# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

# Simple pre-commit configuration for the root repository
# Focuses on basic file checks without interfering with submodule configs

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(grian-ui/|refernce/)
      - id: end-of-file-fixer
        exclude: ^(grian-ui/|refernce/)
      - id: check-merge-conflict
      - id: check-yaml
        exclude: ^(grian-ui/|refernce/)
      - id: check-added-large-files
      - id: mixed-line-ending
        exclude: ^(grian-ui/|refernce/)
